---
title: "Figures for reinfection/ variant paper"
author: "Forrest Jones"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message = FALSE)
```

# Load data and libraries

```{r libraries}

library(tidyverse)
library(cowplot)
library(lubridate)


```


```{r data}

demo <- read_csv("raw_data/individualdemographics.csv") 

routinetesting <- read_csv("raw_data/routinetesting.csv",col_types = paste0(rep("c",24),collapse="")) %>%
        mutate(resultsdate = as.Date(resultsdate),
               collectdate = as.Date(collectdate),
               onsetdate = as.Date(onsetdate)) %>%
        rename(result0=result) %>%
        mutate(result=recode(result0,
                             "positive" = "Positive",
                             "POSITIVE" = "Positive",
                             "Positive" = "Positive",
                             "Detected" = "Positive",
                             "COMPLIANT: PLEASE SUBMIT YOUR NEXT SAMPLE AS SCHEDULED" = "Negative",
                             "NOT RECOMMENDED FOR DIAGNOSTIC TESTING"="Negative" ,

                             "NEGATIVE" = "Negative",
                             "Negative" = "Negative",

                             .default = "Other")) %>%
        left_join(demo) %>%
        #adjust the variants
        mutate(vResult= ifelse(is.na(variant),result,variant)) %>%
        mutate(vResult1 = recode(vResult,
                                 "Negative"="Negative/Other/None",
                                 "Other"="Negative/Other/None",
                                 "None"="Negative/Other/None",
                                 "Positive"="Positive, not typed"#,
                                 # "B.1.596"="B.1.596",
                                 # "B.1.2"="B.1.2",
                                 # "B.1.1.7" = "B.1.1.7"
                                 #
                                 #
                                 # .default = "Other Variant"






        )) %>%
        mutate(n_ct=as.numeric(n_ct),
               s_ct=as.numeric(s_ct),
               orf1ab_ct=as.numeric(orf1ab_ct),
               ms2_ct=as.numeric(ms2_ct)
               )

        
contact_data <- read_csv("raw_data/closecontacts.csv")
        
pos_tests <- routinetesting %>% filter(result=="Positive") 
        

```

# Reinfection Figure

```{r}


firstinfection <- pos_tests %>% group_by(uid) %>%
                        summarize(first=min(collectdate)) %>%
                        filter(first+90<=today())


repeatcases <- pos_tests %>%
                group_by(uid) %>%
                mutate(count=n()) %>%
                filter(count>=2)

repeatcases2 <- repeatcases %>%
                        group_by(uid) %>%
                        summarize(max=max(collectdate),min=min(collectdate),
                                  diff=max(collectdate)-min(collectdate))  %>%
                        filter(diff>=30) %>%
                        arrange(uid)


reinfection_demo <- demo %>%
                        filter(uid %in% repeatcases2$uid) %>%
                        left_join(repeatcases2)


DT::datatable(reinfection_demo)

pos_tests %>% filter(uid %in% repeatcases2$uid) %>% 
        select(uid,collectdate,resultsdate,result0,result,
               laboratory,test_name,vResult1
               ) %>%
        arrange(uid,collectdate) %>%
        write_csv("test_results_reinfection.csv")



reinfections <- routinetesting %>%
        filter(uid %in% repeatcases2$uid) %>%
        mutate(lastpos=ifelse(result=="Positive",as.character(collectdate),"1999-01-01")) %>%
        group_by(uid) %>%
        mutate(lastpos=max(as.Date(lastpos)))

#with lab
fig1 <- reinfections %>% arrange(uid,collectdate,result)%>%
        
        ggplot(aes(x=collectdate,y=reorder(paste0(substr(uid,1,8),"..."),lastpos)))+
        geom_line(aes(group=uid))+
        geom_point(aes(col=result,shape=laboratory
                       ),size=2)+
        geom_text(data = repeatcases2,nudge_y=0.35,
                  aes(x=max-5,y=reorder(paste0(substr(uid,1,8),"..."),max),
                      label=paste0(as.numeric(diff)," days"))
                  )+
        geom_rug(data= distinct(pos_tests,collectdate,uid),
                 aes(x=collectdate), sides="b",inherit.aes = FALSE,
                 col="darkorange",alpha=0.05 
                 )+
        scale_color_manual("Result",values=c("blue","black","red"))+
        theme_bw()+
        ylab("UID")+
        scale_x_date("Date of Collection", 
                     breaks = unique(floor_date(reinfections$collectdate ,"months") ),
                     minor_breaks = NULL
                     )+
        scale_shape_manual("Laboratory",values = c(15,7,16,1,17))+
        theme(axis.text.x = element_text(angle=45,hjust=1))


fig1

```



```{r}

#with variants
fig2 <- reinfections %>% arrange(uid,collectdate,result)%>%
        mutate(vResult1=factor(vResult1,
                               levels = c(
                                       "Positive, not typed",
                                       "B.1.596",
                                       "B.1.2","B.1","P.1",
                                       "B.1.243","B.1.1.7",
                                       "B.1.588","B.1.517",
                                       "B.1.362","B.1.110.3",
                                       "B.1.1.329","Negative/Other/None" )

                               )) %>%
        
        ggplot(aes(x=collectdate,y=reorder(paste0(substr(uid,1,8),"..."),lastpos)))+
        geom_line(aes(group=uid))+
        geom_point(aes(col=vResult1#,shape=laboratory
        ),size=2)+
        geom_text(data = repeatcases2,nudge_y=0.35,
                  aes(x=max-5,y=reorder(paste0(substr(uid,1,8),"..."),max),
                      label=paste0(as.numeric(diff)," days"))
        )+
        geom_rug(data= distinct(pos_tests,collectdate,uid),
                 aes(x=collectdate), sides="tr",inherit.aes = FALSE,
                 col="darkorange",alpha=0.05 ,outside=TRUE
        )+
        coord_cartesian(clip = "off")+
        scale_color_manual("Result",values=c(RColorBrewer::brewer.pal(12,"Paired")[c(6,1:5,7:12)],
                                             "black"

                                             ))+
        theme_bw()+
        ylab("UID")+
        scale_x_date("Date of Collection", 
                     breaks = unique(floor_date(reinfections$collectdate ,"months") ),
                     minor_breaks = NULL
        )+
        scale_shape_manual("Laboratory",values = c(15,7,16,1,17))+
        theme(axis.text.x = element_text(angle=45,hjust=1),
              plot.margin = margin(1, 1, 1, 1, "cm")
              
              )






fig2

ggsave(plot=fig2,filename="figures/reinfection_figures/reinfection.pdf",
       width = 9.3,height=7.5
       
       )




```

# Stoke Hall Figure

```{r stoke-hall}

# woodside <- demo %>% distinct(dorm) %>%
#                         filter(str_detect(dorm, "Woodside"))
the_dorm <- "Stoke Hall" #woodside$dorm

stokehall_people <- demo %>% filter(dorm %in% the_dorm)

stokehall_quarantines1 <- contact_data %>% filter(quarantine_person %in% stokehall_people$uid) 


stokehall_cases1 <- pos_tests %>%
        #focus on things only after february 1st
        filter(collectdate >=as.Date("2021-02-01")) %>%
        #limit to cases that are from stoke hall or infect people in stoke hall
        filter(dorm %in% the_dorm | uid %in% stokehall_quarantines1$close_contact) %>%
        mutate(dorm=ifelse(is.na(dorm),paste("Off-Campus",user_status),dorm)) %>%
        #make sure to only have one row per person
        distinct(uid,collectdate,dorm,vResult1,variant) %>%
        #take the first infection only (can modify later)
        group_by(uid,dorm, collectdate) %>%
        filter(n()==1 | !is.na(variant)) %>%
        #take the first infection only (can modify later)
        group_by(uid,dorm) %>%
        filter(collectdate==min(collectdate))

#check that people are not listed as cases twice
stokehall_cases1 %>% group_by(uid) %>%
        filter(n()>1)       

#quarantines associated are 14 days before the infection
stokehall_quarantines2 <- stokehall_quarantines1 %>%
                                left_join(stokehall_cases1,by=c("quarantine_person"="uid")) %>%
                                filter(qt_entry_date >= collectdate-14) %>%
                                distinct(quarantine_person,close_contact,qt_entry_date) 


#check that people are not listed in quarantine twice
stokehall_quarantines2 %>% group_by(quarantine_person) %>%
                filter(n()>1)


#add the contacts
stokehall_cases2 <- stokehall_cases1 %>% 
        left_join(stokehall_quarantines2, by=c("uid"="quarantine_person")) %>%
        #if the both the close contact and quarantined person are outside of stoke hall
        # change the close contact to NA
        mutate(close_contact = ifelse((!close_contact %in% stokehall_people$uid ) &
                                              (!uid %in% stokehall_people$uid),
                                      NA,close_contact
               )) %>%
        # if close contact does not have a uid, change to NA
        mutate(close_contact =ifelse(close_contact %in% demo$uid,close_contact,NA)) %>%
        arrange(collectdate)

#check that cases are repeated again
stokehall_cases2 %>% group_by(uid) %>%
        filter(n()>1)

#assign those not connected as 0 cluster
stokehall_cases_clustered <-  stokehall_cases2 %>%
        mutate(cluster=ifelse(uid %in%stokehall_cases2$close_contact,NA,0))


#go through each case and find clusters AND pairs in order of collect date
cluster_counter <- 1

#blank pairs df
pairs_df <- data.frame()

for (i in stokehall_cases_clustered$uid){
        
        #starting case, date, and cluster
        this_case <- filter(stokehall_cases_clustered, uid == i)
        
        # if the case has not been assigned a cluster
        if(is.na(this_case$cluster)){
                #assign cluster to individual
                stokehall_cases_clustered <- stokehall_cases_clustered %>%
                        mutate(cluster=ifelse(uid==i,cluster_counter,cluster))
                this_case$cluster <- cluster_counter
                #move counter
                cluster_counter <- cluster_counter + 1
        }

        #contacts of individual i
        contacts <- stokehall_cases_clustered %>%
                        filter(close_contact==i) %>%
                        filter(collectdate-14 < this_case$collectdate)
        
        pairs_df <-bind_rows(pairs_df,
                             data.frame(contacts=contacts$uid) %>%
                                     mutate(case=i)
                             )

        stokehall_cases_clustered <- stokehall_cases_clustered %>%
                mutate(cluster=ifelse(uid %in% contacts$uid,this_case$cluster,cluster))

        
}


#remove non clustered non-stoke dorm peopl
stokehall_cases_clustered <- stokehall_cases_clustered %>% 
                        filter(!(cluster==0 & !(dorm %in% the_dorm)))



#number of facets to be used in the graph
groups <- 7

graph_df_points <- stokehall_cases_clustered %>% 
                        mutate(group=ifelse(cluster==0,groups/2+0.25,(cluster %% groups) +1)) %>%
                        group_by(collectdate,group) %>%
                        mutate(count=1)%>%
                        mutate(count=cumsum(count)) %>%
                        # mutate(count=count+rnorm(n(),sd=0.2)) %>%
                        mutate(count=count-max(count)/2) %>%
                        ungroup() 




graph_df_lines2 <-   pairs_df %>% left_join(select(graph_df_points,uid,collectdate,count,cluster,group),by=c("case"="uid")) %>%
                        left_join(select(graph_df_points,uid,collectdate,cluster,count),by=c("contacts"="uid")) %>%
                        # mutate(curvy=collectdate.y-collectdate.x)
                        mutate(curvy=cumprod(rep(-1,nrow(.)))) %>%
                        #curve up
                        mutate(curvy=ifelse(count.x>count.y,1,curvy)) %>%
                        #curve down
                        mutate(curvy=ifelse(count.x<count.y,-1,curvy)) #%>%
                        # #straight line
                        # group_by(cluster.x) %>%
                        # arrange(collectdate.y) %>%
                        # mutate(order=1:n()) %>%
                        # mutate(curvy= ifelse(order==1 & count.x==count.y,0,curvy))
        
        
        
                        
        
        
        
 
graph_df_points%>%
        ggplot()+
        geom_curve(data=filter(graph_df_lines2,curvy==-1), curvature=-0.2,
                  aes(x=collectdate.x,y=count.x,xend=collectdate.y,yend=count.y
                      ))+
        geom_curve(data=filter(graph_df_lines2,curvy==1), curvature=0.2,
                   aes(x=collectdate.x,y=count.x,xend=collectdate.y,yend=count.y
                   ))+
        # geom_curve(data=filter(graph_df_lines2,curvy==0), curvature=0,
        #            aes(x=collectdate.x,y=count.x,xend=collectdate.y,yend=count.y
        #            ))+
        geom_point(aes(x=collectdate,y=count,col=vResult1,shape=dorm)) +
        facet_grid(reorder(group,-group)~., #scales="free_y",
                   space = "free_y")+
        theme_cowplot()+
        theme(
              strip.background = element_blank(),
              strip.text = element_blank(),
              axis.text.y= element_blank(),
              axis.line.y =  element_blank(),
              axis.ticks.y =   element_blank(),
              axis.title.y =   element_blank() ,
              panel.spacing =  unit(0, "lines")
        )+
        xlab("Date of Collection")


#straight line graph

# graph_df_lines <-  bind_rows(
#         
#         
#                         select(graph_df_points,uid,collectdate,count,group) %>%
#                                 right_join(mutate(pairs_df,pair_id= 1:n()), by=c("uid"="case")),
#                         select(graph_df_points,uid,collectdate,count,group) %>%
#                                 right_join(mutate(pairs_df,pair_id= 1:n()), by=c("uid"="contacts")),
#                         
#                         
#                         )
# 
# 
#                         
#                         
#                                 
# 
# graph_df_points%>%
#                         ggplot()+
#                         geom_point(aes(x=collectdate,y=count,col=dorm)) +
#                         geom_line(data=graph_df_lines,
#                                   aes(x=collectdate,y=count,group=pair_id))+
#                         facet_grid(group~.,scales="free_y",
#                                    space = "free_y")+
#                         theme_cowplot()+
#                         theme(strip.background = element_blank(),
#                               strip.text = element_blank(),
#                               axis.text.y= element_blank(),
#                               axis.line.y =  element_blank(),
#                               axis.ticks.y =   element_blank(),
#                               axis.title.y =   element_blank() 
#                               )
# 




```


# Investigate protective efficacy and transmission efficacy

Look only at contacts to see the protective efficacy of reinfections and how well people who are reinfected are at spreading the virus

```{r}


infection2020 <- filter(pos_tests, year(collectdate)==2020)%>%
        distinct(uid,collectdate)
infection2021 <- filter(pos_tests, year(collectdate)==2021) %>%
                        distinct(uid,collectdate) %>%
                        group_by(uid) %>%
                        summarize(collectdate=min(collectdate))





#protective efficacy

ar_df <- contact_data %>% select(-close_contact) %>%
        mutate(infected2020=quarantine_person %in% infection2020$uid) %>%
        left_join(infection2021,by=c(quarantine_person="uid")) %>%
        mutate(infected2021= collectdate-as.Date(qt_entry_date) <14) %>%
        mutate(infected2021 = ifelse(is.na(infected2021),FALSE,TRUE))
        

ar_df%>% 
        group_by(infected2020,infected2021) %>%
        summarize(contacts=n())

ar_df %>% group_by(infected2020) %>%
                summarize(AR=mean(infected2021)) %>%
                mutate(ARR=AR/max(AR)) %>%
                mutate(PE=1-ARR)


 #efficacy of transmission

trans_df <- contact_data %>% 
        left_join(select(reinfection_demo,uid,max), by=c("close_contact"="uid")) %>% 
        mutate(reinfector=as.Date(qt_entry_date)-max<14)  %>%
        mutate(reinfector=ifelse(is.na(reinfector),FALSE,reinfector))  %>%
        left_join(infection2021,by=c(quarantine_person="uid")) %>%
        mutate(infected2021= collectdate-as.Date(qt_entry_date) <14) %>%
        mutate(infected2021 = ifelse(is.na(infected2021),FALSE,TRUE))


trans_df%>% 
        group_by(reinfector,infected2021)  %>%
        summarize(contacts=n())


trans_df%>% 
        group_by(reinfector) %>%
        summarize(AR=mean(infected2021)) %>%
        mutate(ARR=AR/min(AR)) 
        

     


```


```{r}

reinfection_ct <- pos_tests %>% filter(uid %in% reinfection_demo$uid) %>%
                arrange(uid,collectdate) %>%
                group_by(uid) %>%
                mutate(degree=1:n()) %>%
                mutate(positives=n()) %>%
                filter(!is.na(n_ct)) %>%
                mutate(degree=ifelse(positives==3,degree-1,degree)) %>%
                select(uid,collectdate,degree,n_ct) 


reinfection_ct %>% group_by(degree) %>%
                count()


reinfection_ct %>% ggplot(aes(y=n_ct,x=factor(degree)))+
                geom_boxplot()+
                geom_jitter(height=0)+
                xlab("Infection")+
                ggtitle("Comparison of Ct values in reinfected individuals")


t.test(data=reinfection_ct, n_ct ~ degree)

```


# Make sure that each row is a distinct cases


```{r}

contact_data <- read_csv("raw_data/closecontacts.csv")
        
# imperfect cases but will work for now
# need to deal with definitions of positive and variants

all_cases <- routinetesting %>% filter(result=="Positive" & vResult1 != "Negative/Other/None")  %>%
                        # if collect date missing, put result date
                        mutate(date=ifelse(is.na(collectdate),as.character(resultsdate),as.character(collectdate))) %>%
                        mutate(date=as.Date(date)) %>%
                        select(uid,date,result,vResult1) %>%
                        arrange(uid,date) %>%
                        group_by(uid) %>% 
                        mutate(n=n(),
                               min_date = min(date),
                               max_date = max(date),
                               range=as.numeric(max_date-min_date)      
                               )

single_cases <- filter(all_cases,n==1)

potential_reinfections <- filter(all_cases, n>1 & range>=80)%>%
                        # if some positive results have variant results and others dont,take the one where its been typed
                        mutate(vResult1=ifelse(vResult1=="Positive, not typed","",vResult1)) %>%
                        group_by(uid,date,result) %>%
                        summarize(vResult1=paste0(vResult1,collapse = "")) %>%
                        mutate(vResult1=ifelse(vResult1=="","Positive, not typed",vResult1)) %>%
                        group_by(uid) %>%
                        mutate(n=n())

summary(potential_reinfections)


not_reinfections <- filter(all_cases,n>1 & range<80) %>%
                        #use the first positive date
                        group_by(uid) %>%
                        mutate(date=min(date)) %>%
                        #remove any duplicates for variant results
                        distinct(uid,date,result,vResult1) %>%
                        # if some positive results have variant results and others dont,take the one where its been typed
                        mutate(vResult1=ifelse(vResult1=="Positive, not typed","",vResult1)) %>%
                        group_by(uid,result,date) %>%
                        summarize(vResult1=paste0(vResult1,collapse = "")) %>%
                        mutate(vResult1=ifelse(vResult1=="","Positive, not typed",vResult1)) %>%
                        group_by(uid) %>%
                        mutate(n=n())

summary(not_reinfections)


final_cases <- bind_rows(single_cases,potential_reinfections,not_reinfections) %>%
                                                select(uid,date,vResult1) 



```


# case pairs

```{r}

case_pairs <- contact_data %>%
                        rename(quar_person=quarantine_person,
                               inf_person=close_contact,
                               quar_entry_date=qt_entry_date) %>%
                        mutate(quar_entry_date=as.Date(quar_entry_date)) %>%
                        #limit those where both are in the case file
                        filter(quar_person %in% final_cases$uid) %>%
                        filter(inf_person %in% final_cases$uid) %>%
                        #bring in the case_data
                        left_join(final_cases, by=c("quar_person"="uid")) %>%
                        rename(quar_pos_date=date,quar_variant=vResult1) %>%
                        left_join(final_cases, by=c("inf_person"="uid")) %>%
                        rename(inf_pos_date=date,inf_variant=vResult1) %>%
                        #calculate time from quarantine to positive
                        mutate(days_quar_pos=as.numeric(quar_pos_date-quar_entry_date)) %>%
                        #calculate time between positives
                        mutate(days_pos_pos=as.numeric(quar_pos_date-inf_pos_date)) %>%
                        # limit to those where the quarantine date is close to
                        # the positive date
                        filter(days_quar_pos<=14 & days_quar_pos >=-2) %>%
                        filter(days_pos_pos<=14 & days_pos_pos >=0)



case_pairs %>% group_by(inf_variant,quar_variant) %>%
                count() %>%
                filter(quar_variant!=inf_variant) %>%
                filter(quar_variant!="Positive, not typed") %>%
                filter(inf_variant!="Positive, not typed" ) %>%
                rename(Infector=inf_variant,
                       Infectee=quar_variant
                       ) %>%
                flextable::flextable()





```



```{r}

the_dorm <- "Stoke Hall" #woodside$dorm

stokehall_people <- demo %>% filter(dorm %in% the_dorm)

stoke_cases <- filter(single_cases, uid %in% stokehall_people$uid)
stoke_pairs <- filter(case_pairs, quar_person %in% stoke_cases$uid) %>%
                filter(inf_person %in% stoke_cases$uid)




```

```{r}
pacman::p_load(
   rio,          # File import
   here,         # File locator
   tidyverse,    # Data management + ggplot2 graphics
   remotes       # Package installation from github
)

# pacman::p_install_gh("reconhub/epicontacts@timeline")
library(epicontacts)

```


```{r}


epic <- make_epicontacts(
  linelist = stoke_cases,
  contacts = stoke_pairs,
  id = "uid",
  from = "inf_person",
  to = "quar_person",
  directed = TRUE
)

hi <- plot(epic,x_axis = "date",
       label = FALSE,
     node_color = "vResult1",
       network_shape = "rectangle",
     arrow_size = 0.3,
        node_size = 8,

)

hi

```
