---
output: 
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: journal
params:
  run_checks: TRUE # whether to run and print out basic data checks
  show_cleaning: TRUE # whether to print out basic info about data cleaning steps
  report_date: "2020-10-12" # date in YYYY-MM-DD
---


```{r setup, include=FALSE}
  knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
  knitr::opts_knit$set(eval.after = 'fig.cap')

  fig_counter <- 1
  
  library(tidyverse)
  library(glue)
  library(colorspace)
  library(flextable)
  
```

```{r data-load}

#should we set warning=TRUE here to see parsing errors???? or is this potentially showing us data we arent allowed to see?

  routinetesting <- read_csv("raw_data/routinetesting.csv") %>%
                    mutate(resultsdate = as.Date(resultsdate),
                           collectdate = as.Date(collectdate),
                           onsetdate = as.Date(onsetdate)) %>%
                    mutate(sample_id_gen=1:nrow(.))

  isolationquarantine <- read_csv("raw_data/isolationquarantine.csv")

  individualdemographics <- read_csv("raw_data/individualdemographics.csv")

```

```{r params}

  report_date <- as.Date(params$report_date)
  report_date_str_long <- as.character(format(report_date, format="%B %d, 2020"))
  report_date_str_short <- as.character(format(report_date, format="%b %d"))
  
  # Date on which report begins
  start_date <- report_date - 7
  start_date_str_long <- as.character(format(start_date, format="%B %d, 2020"))
  start_date_str_short <- as.character(format(start_date, format="%b %d"))
  
  # Date to which active cases are counted
  report_date_minus10 <- report_date - 10
  
  # one week date
  report_date_minus7 <- report_date - 7
  
  # two week date
  report_date_minus14 <- report_date - 14

```


```{r demo-checks, eval=params$run_checks}
  ## print out missingness in demographics
  summary(is.na(individualdemographics))

  ## print out how many repeat IDs there are by campus and user status
  individualdemographics %>%
          group_by(uid) %>%
          summarize(n = n(),
                    campus = campus[1],
                    user_status = user_status[1]) %>%
          filter(n > 1) %>%
          ungroup() %>%
          group_by(campus, user_status) %>%
          summarize(n = n())

```

```{r demo-duplicates}
  
  ## remove duplicates if they still exist
  ## favor entries that have complete campus, age, user_status where available
  ## logic: add number of missing values (of campus, age, user_status, )
  ## arrange data so that NAs are last, then fill in NAs
  ## keep the row that had the fewest elements filled in
  individualdemographics <- individualdemographics %>%
                            group_by(uid) %>%
                            mutate(n_missing = sum(is.na(c(user_status, sex, age, campus)), na.rm=TRUE)) %>%
                            arrange(user_status) %>%
                            fill(user_status) %>%
                            arrange(sex) %>%
                            fill(sex) %>%
                            arrange(age) %>%
                            fill(age) %>%
                            arrange(campus) %>%
                            fill(campus) %>%
                            arrange(n_missing) %>%
                            mutate(n = 1:n()) %>%
                            ungroup() %>%
                            filter(n==1)
        
```


```{r demo-recoding, include=params$show_cleaning}

  ## numeric categorical for user_status
  ## 0, student; 1, faculty; 2, staff; 3, employee; 4, unknown
  table(individualdemographics$user_status)
  individualdemographics <- individualdemographics %>%
                            mutate(user_status = tolower(user_status)) %>%
                            mutate(user_status_num = recode(user_status,
                                                            student = 0,
                                                            faculty = 1,
                                                            staff = 2,
                                                            employee = 3,
                                                            unknown = 4),
                                   user_status_fac = factor(user_status_num,
                                                            levels = 0:4,
                                                            labels = c("Student", "Faculty", "Staff", "Employee", "Unknown")))
  table(individualdemographics$user_status, individualdemographics$user_status_num)
  table(individualdemographics$user_status, individualdemographics$user_status_fac)
  
  ## numeric age categories
  ## [15, 20), then 10y bins to 80+
  table(individualdemographics$age)
  individualdemographics <- individualdemographics %>%
                            mutate(age_cat = cut(age, breaks=c(15, seq(20, 80, 10), 200), right = FALSE),
                                   age_cat_num = as.numeric(age_cat),
                                   age_cat = factor(age_cat,
                                                    labels = c("15-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80+")))
  table(individualdemographics$age_cat_num, individualdemographics$age_cat)
  table(individualdemographics$age, individualdemographics$age_cat)

  ## numeric gender categories from `sex`
  table(individualdemographics$sex)
  individualdemographics <- individualdemographics %>%
                            mutate(sex = tolower(sex)) %>%
                            mutate(gender=recode(sex,
                                                 "cisgender man"="Assigned Male at Birth",
                                                 "cisgender woman"="Assigned Female at Birth",
                                                 "male"="Assigned Male at Birth",
                                                 "female"="Assigned Female at Birth",
                                                 "transgender wan"= "Trans Man",
                                                 "transgender woman"= "Trans Woman",
                                                 "gender non-Conforming"= "Genderqueer/Non-binary (GNB)",
                                                 "gender queer"="Genderqueer/Non-binary (GNB)",
                                                 "non-binary"= "Genderqueer/Non-binary (GNB)",
                                                 "my identity is not listed"= "Not listed or prefer not to say",
                                                 "prefer not to say"="Not listed or prefer not to say"
                                                 )) %>%
                            mutate(gender=factor(gender,levels=c("Assigned Male at Birth",
                                                                 "Assigned Female at Birth",
                                                                 "Trans Man",
                                                                 "Trans Woman",
                                                                 "Genderqueer/Non-binary (GNB)",
                                                                 "Not listed or prefer not to say"))) %>%
                            mutate(gender_num = as.numeric(gender) - 1)
    table(individualdemographics$sex, individualdemographics$gender)
    table(individualdemographics$gender_num, individualdemographics$gender)
                                        

  ## numeric campus indicator
  ## 0 "Durham"; 1 "Concord (Law)"; 2 "Manchester"; 3 "Other"
  table(individualdemographics$campus)
  individualdemographics <- individualdemographics %>%
                            mutate(campus = tolower(campus)) %>%
                            mutate(campus_num=recode(campus,
                                                 "unh durham" = 0,
                                                 "unh law"= 1,
                                                 "unh manchester" = 2,
                                                 "other" = 3)) %>%
                            mutate(campus_fac=factor(campus_num,
                                                     levels = 0:3,
                                                     labels = c("UNH Durham","UNH Law","UNH Manchester","Other")),
                                   campus_num=as.numeric(campus_fac)-1)
  table(individualdemographics$campus, individualdemographics$campus_fac)
  table(individualdemographics$campus_num, individualdemographics$campus_fac)

  ## numeric program result
	## 0 "Lib Arts"; 1 "Business";	2 "Agriculture"; 3 "Engineering"; 4 "Health"; 5 "Graduate School";
  ## 6 "Continuing Ed"; 7 "Manchester"; 8 "Law";	9 "Applied Sciences"
  table(individualdemographics$college)
  individualdemographics <- individualdemographics %>%
                            mutate(college_num = tolower(college),
                                   college_num = str_replace(college_num, ".*liberal arts.*", "0"),
                                   college_num = str_replace(college_num, ".*business.*", "1"),
                                   college_num = str_replace(college_num, ".*life science.*", "2"),
                                   college_num = str_replace(college_num, ".*engineer.*", "3"),
                                   college_num = str_replace(college_num, ".*health.*", "4"),
                                   college_num = str_replace(college_num, ".*graduate.*", "5"),
                                   college_num = str_replace(college_num, ".*continuing.*", "6"),
                                   college_num = str_replace(college_num, ".*manchester.*", "7"),
                                   college_num = str_replace(college_num, ".*law.*", "8"),
                                   college_num = str_replace(college_num, ".*applied.*", "9"),
                                   college_num = str_replace(college_num, ".*designated.*", "10")) %>%
                            mutate(college_num = as.numeric(college_num)) %>%
                            mutate(college_fac = factor(college_num,
                                                        levels = 0:10,
                                                        labels = c("Liberal Arts",
                                                                   "Business",
                                                                   "Agriculture",
                                                                   "Engineering",
                                                                   "Health",
                                                                   "Graduate School",
                                                                   "Continuing Ed",
                                                                   "Manchester",
                                                                   "Law",
                                                                   "Applied Sciences",
                                                                   "No college designated")))
  table(individualdemographics$college, individualdemographics$college_fac)
  table(individualdemographics$college_num, individualdemographics$college_fac)

  
  ## dorimtory + on/off campus levels
  ## On/Off: 1 if no dorm listed
  ## Dorm: 0 "Hills" 1 "Valley" 2 "Timbers" 3 "Woodside Apts" 4 "Gables Apts"
      # note the that no students are listed in the isolation and quarantine dorm:
      # https://www.unh.edu/housing/residence-halls
      # Adams Tower West and Babcock Hall are being utilized as UNH's isolation and quarantine dorms.
      # Adams Tower West has single rooms with ensuite bathrooms.
      # Babcock Hall offers single residence hall rooms with community bathrooms.
      # Students assigned to the Quarantine or Isolation Halls will be provided meals, snacks and beverages.

  table(individualdemographics$dorm)
  individualdemographics <- individualdemographics %>%
                            mutate(off_campus_num=ifelse(is.na(dorm), 1, 0),
                                   off_campus_fac = factor(off_campus_num,
                                                          levels = 0:1,
                                                          labels = c("On Campus", "Off Campus"))) %>%
                            mutate(dorm_group=recode(dorm,
                                                     "Alexander Hall"= "The Valley", 
                                                     "Christensen Hall"= "The Timbers",
                                                     "Congreve Hall"= "The Hills",
                                                     "Devine Hall" = "Upper Quad",
                                                     "Eaton House" = "The Minis",
                                                     "Engelhardt Hall"="The Valley",
                                                     "Fairchild Hall"="The Valley",
                                                     "Gables North" = "Gables Apts",   
                                                     "Gables South" = "Gables Apts",       
                                                     "Gibbs Hall"= "The Valley",
                                                     "Haaland Hall" = "The Timbers",
                                                     "Hall House" = "The Minis",
                                                     "Handler Hall"= "The Timbers",
                                                     "Hetzel Hall" = "The Valley",
                                                     "Hitchcock Hall"= "Upper Quad",
                                                     "Hubbard Hall" = "The Timbers",
                                                     "Hunter Hall" = "The Valley",
                                                     "Jessie Doe Hall"="The Hills", 
                                                     "Lord Hall"="The Hills",    
                                                     "Marston House" = "The Minis",
                                                     "Mclaughlin Hall"="The Hills",
                                                     "Mills Hall"="The Valley",
                                                     "Peterson Hall"="The Timbers",
                                                     "Randall Hall" = "Upper Quad",
                                                     "Richardson House" = "The Minis",
                                                     "Sawyer Hall"="The Hills",
                                                     "Scott Hall"="The Hills",
                                                     "Stoke Hall"="The Hills",
                                                     "The Gables - A" = "Gables Apts",
                                                     "The Gables - B" = "Gables Apts",
                                                     "The Gables - C" = "Gables Apts",
                                                     "Williamson Hall"="The Timbers",
                                                     "Woodside Apts. A" = "Woodside Apts",
                                                     "Woodside Apts. B" = "Woodside Apts",
                                                     "Woodside Apts. C" = "Woodside Apts",
                                                     "Woodside Apts. D" = "Woodside Apts",
                                                     "Woodside Apts. E" = "Woodside Apts",
                                                     "Woodside Apts. F" = "Woodside Apts",
                                                     "Woodside Apts. G" = "Woodside Apts",
                                                     "Woodside Apts. H"= "Woodside Apts",
                                                     "Woodside Apts. I"= "Woodside Apts",
                                                     "Woodside Apts. J"= "Woodside Apts",
                                                     "Woodside Apts. K"= "Woodside Apts",
                                                     "Woodside Apts. L"= "Woodside Apts",
                                                     "Woodside Apts. M"= "Woodside Apts",
                                                     "Woodside Apts. N"= "Woodside Apts",
                                                     "Woodside Apts. O"= "Woodside Apts",
                                                     "Woodside Apts. P"= "Woodside Apts",
                                                     "Woodside Apts. Q"= "Woodside Apts",
                                                     "Woodside Apts. R"= "Woodside Apts")) %>%
                            mutate(dorm_group_num = recode(dorm_group,
                                                           "The Hills" = 0,
                                                           "The Valley" = 1,
                                                           "The Timbers" = 2,
                                                           "Woodside Apts" = 3,
                                                           "Gables Apts" = 4),
                                   dorm_group = as.factor(dorm_group))
  table(individualdemographics$dorm, individualdemographics$off_campus_num)
  table(individualdemographics$off_campus_fac, individualdemographics$off_campus_num)
  table(individualdemographics$dorm, individualdemographics$dorm_group)
  table(individualdemographics$dorm_group_num, individualdemographics$dorm_group)

```


```{r demo-testing-merge}
  
  ## merge the testing and demographics datasets
  demo_testing <- routinetesting %>%
                    left_join(individualdemographics, by="uid")
    
```


```{r demo-testing-merge-checks, eval=params$run_checks}

  ## missingness
  summary(is.na(demo_testing))

  ## are the dimensions of `demo_testing` the same as `routine_testing`
  nrow(demo_testing) == nrow(routinetesting)

  ## how many IDs have no testing information ever, in last 1 week, or in last 2 weeks? 
  tmp <- demo_testing %>%
         mutate(tested_1week = ifelse((resultsdate > report_date_minus7 & resultsdate <= report_date) | 
                               (collectdate > report_date_minus7 & collectdate <= report_date), 1, 0),
                tested_2week = ifelse((resultsdate > report_date_minus14 & resultsdate <= report_date) | 
                               (collectdate > report_date_minus14 & collectdate <= report_date), 1, 0))
  
  individualdemographics %>%
    group_by(campus, user_status) %>%
    summarise(n_never_tested = sum(!(uid %in% tmp$uid), na.rm=TRUE),
              n_not_tested_2week = sum(!(uid %in% tmp$uid[tmp$tested_2week==1])),
              n_not_tested_1week = sum(!(uid %in% tmp$uid[tmp$tested_1week==1])))
  
  ## how complete does the testing data look for report period?
  ## using collectdate, which appears to be more complete
  tmp %>%
    filter(tested_1week == 1) %>%
    group_by(collectdate) %>%
    summarise(n_tests = n())
  
```


```{r isolation-recoding, include=params$show_cleaning}

  ## Recoding dates, date-times
  isolationquarantine <- isolationquarantine %>%
                         mutate(quar_entrydttm = as.POSIXct(quar_entrydate),
                                quar_exitdttm = as.POSIXct(quar_exitdate),
                                quar_exposuredttm = as.POSIXct(quar_exposuredate),
                                iso_entrydttm = as.POSIXct(iso_entrydate),
                                iso_exitdttm = as.POSIXct(iso_exitdate),
                                quar_entrydate = as.Date(quar_entrydate),
                                quar_exitdate = as.Date(quar_exitdate),
                                quar_exposuredate = as.Date(quar_exposuredate),
                                iso_entrydate = as.Date(iso_entrydate),
                                iso_exitdate = as.Date(iso_exitdate),
                                notifydttm = as.POSIXct(notifydate),
                                notifydate = as.Date(notifydate))

  ## Recoding location
  table(isolationquarantine$location)
  table(isolationquarantine$dorm)
  isolationquarantine <- isolationquarantine %>%
                         mutate(quar_isol_bed = ifelse(location=="Campus", 1, 0)) %>%
                         rename(dorm_isol = dorm)
  
```

```{r demo-isolation-merge}

  ## merge the isolation and demographics datasets
  demo_isol <- isolationquarantine %>%
               left_join(individualdemographics, by="uid")

```


```{r demo-isolation-checks, eval=params$run_checks}

  ## how many isolation/quar events don't have demo data?
  summary(is.na(demo_isol))
  
  ## how many listed more than once?
  demo_isol %>%
    mutate(quar_ind = ifelse(is.na(quar_entrydate), 0, 1),
           isol_ind = ifelse(is.na(iso_entrydate), 0, 1)) %>%
    group_by(uid) %>%
    summarise(n = n(),
              n_quar = sum(quar_ind),
              n_isol = sum(isol_ind)) %>%
    ungroup() %>%
    summarise(n_quar_morethanonce = sum(n_quar>1, na.rm=TRUE),
              n_quar_morethantwice = sum(n_quar>2, na.rm = TRUE),
              n_isol_morethanonce = sum(n_isol>1, na.rm=TRUE),
              n_quar_and_isol = sum(n_isol>0 & n_quar>0, na.rm = TRUE))
  
  ## any overlapping quarantine periods?
  demo_isol %>%
    group_by(uid) %>%
    filter(sum(!is.na(quar_entrydate)) > 1) %>%
    arrange(uid, quar_entrydate) %>%
    mutate(prev_quarexit = lag(quar_exitdate)) %>%
    mutate(overlap = ifelse(prev_quarexit > quar_entrydate, 1, 0)) %>%
    ungroup() %>%
    filter(overlap==1) %>%
    group_by(campus, user_status) %>%
    summarise(n_overlapping_quar = n())
    

```

```{r isol-duplicates}
  
  ## remove duplicate/overlapping quarantines if they still exist
  ## favor entries that have complete notification date, location, isolation dorm
  ## first, find the IDs that have overlapping quarantine periods + the two overlapping entries
  ## then select the one to remove

  demo_isol <- demo_isol %>%
               mutate(ind = 1:n())

  to_rm <- demo_isol %>%
           group_by(uid) %>%
           filter(sum(!is.na(quar_entrydate)) > 1) %>%
           arrange(uid, quar_entrydate) %>%
           mutate(prev_quarexit = lag(quar_exitdate)) %>%
           mutate(overlap = ifelse(prev_quarexit > quar_entrydate, 1, 0)) %>%
           mutate(overlap = max(overlap, na.rm = TRUE)) %>%
           filter(overlap == 1) %>%
           mutate(n_missing = sum(is.na(c(notifydate, location)), na.rm=TRUE)) %>%
           arrange(desc(n_missing)) %>%
           mutate(n = 1:n()) %>%
           ungroup() %>%
           filter(n==1)
  
  demo_isol <- demo_isol %>%
               filter(!(ind %in% to_rm$ind))
        
```

```{r demo-testing-long-cleaning, include=params$show_cleaning}

	## Rename variables to be more accurate: collectdate > labeldate, collecttime > labeltime
	demo_testing <- demo_testing %>%
                  rename(labeldate = collectdate,
                         labeltime = collecttime)

  ## numeric test result
	## 0 "Neg"; 1 "Pos"; 2 "Inconclusive"; 3 "Invalid/Rejected/No Result"
  table(tolower(demo_testing$result))
  demo_testing <- demo_testing %>%
                  mutate(result = tolower(result)) %>%
                  mutate(result_num = recode(result,
                                             "negative" = 0,
                                             "positive" = 1,
                                             "test was positive provided letter to be on campus" = 1,
                                             "inconclusive" = 2,
                                             .default = 3)) %>%
                  mutate(result_fac = factor(result_num,
                                             levels = 0:3,
                                             labels = c("Negative", "Positive", "Inconclusive", "Invalid/Rejected/No Result")))
  table(demo_testing$result, demo_testing$result_num)
  table(demo_testing$result_fac, demo_testing$result_num)

	## recode dates
  ## uses resultsdate, unless missing, then uses labeldate
  demo_testing <- demo_testing %>%
                  mutate(testdate = ifelse(is.na(resultsdate), labeldate, resultsdate))

  ## numeric laboratory indicator
  ## 0 "Sequoia"; 1 "Convenient MD"; 2 "Health & Wellness"; 3 "Pre-Arrival"; 4 "Quest"; 5 "Temp UNH Lab"
	table(tolower(demo_testing$laboratory))
  demo_testing <- demo_testing %>%
                  mutate(laboratory = tolower(laboratory)) %>%
                  mutate(laboratory_num = recode(laboratory,
                                             "sequoia" = 0,
                                             "cmd" = 1,
                                             "healthwellnesslab" = 2,
                                             "prearrival" = 3,
                                             "quest" = 4,
                                             "unhlab_temp" = 5)) %>%
                  mutate(laboratory_fac = factor(laboratory_num,
                                             levels = 0:5,
                                             labels = c("Sequoia", "Convenient MD", "Health + Wellness", "Pre-Arrival", "Quest", "UNH Temp.")))
  table(demo_testing$laboratory, demo_testing$laboratory_num)
  table(demo_testing$laboratory_fac, demo_testing$laboratory_num)
  
  ## binary test result indicators in long data - pos, neg, incon, invalid
			# replace pos = 1 if result == 1
			# replace neg = 1 if result == 0
			# replace incon = 1 if result == 2
			# replace invalid = 1 if result == 3
	## labels yes/no


  ## remove duplicate test results (labeldate, resultsdate, result, laboratory)


  ## make sure those positive once do not have positive counted more than once
    ## for each positive test result, check if there is another positive test result in the next 10 days
    ## QUESTION: if there is -- create 'first positive' indicator that should be used for epi curves, etc?

#for now: just remove the any duplicate cases, take the first one with the most recent results date
doublecounted <- demo_testing %>% filter(result_fac=="Positive")  %>%
                arrange(resultsdate)%>%
                filter(duplicated(uid)==TRUE)

#print the number of individuals showing up positive multiple times
nrow(doublecounted)


cases <- demo_testing %>% filter(result_fac=="Positive") %>%
                filter(!(sample_id_gen %in% doublecounted$sample_id_gen))
  
  
```


```{r demo-testing-wide}

  ## by UID, add a sample number # Forrest: already generated this before, see the variable sample_id_gen
  ## then make wide dataset by ID


  ## print out max # of times someone was tested


  ## active case indicator: who had a positive test in the last 10 days report_date_minus10 - report_date
  

  ## 7-day case indicator

  
  ## tested in last 10 days indicator


  ## most recent lab result if tested in past week
    ## pull out most recent test result for anyone tested in last week
    ## (if there is more than one test on the last test date, use the positive)

```


```{r totals-by-date}

  ## data frame: number first positive by campus, role, testdate

  ## data frame: number first positive by campus status, campus, testdate

  ## data frame: number pos, neg, incon, invalid, pos+neg, by campus, role, testdate

  ## data frame: number total tests, by campus, lab, testdate

  ## data frame: number pos, neg, pos+neg by week


  ## long versions of quarantine and isolation

```

# `r glue("UNH SURVEILLANCE REPORT: {report_date}")`
## SECTION A: EXECUTIVE SUMMARY

```{r exec-summary}

  ## source executive summary chunk

```


## SECTION B: UNIVERSITY-WIDE SITUATION

```{r Table-B1A-StateCond}

  ## parse state page for current COVID19 cases, hospitalizations
  ## operation levels with colors

```


```{r Table-B1B-CampusCond}

  # BY CAMPUS + THRESHOLD INDICATOR if applicable
    # Total tests, including repeats
    # Tests per unique ID
    # total positive test results
    # total active cases from last 10 days
    # active cases per 1000 tested
    # average in isolation over last week
    # average isolation beds in use
    # average number in quarantine this week
    # average quarantine beds in use

```


```{r Figure-B1-EpiCurve}

  ## epi curve, new positive, all time, by day, colored by campus

epicurv_df1 <- cases %>% group_by(labeldate,campus)%>%
                summarize(cases=n())

max_ecdf1 <- ceiling(max(epicurv_df$cases)/2)*2

epicurv_df1%>%
        ggplot(aes(x=labeldate,y=cases,fill=campus))+
        geom_col()+
        theme_bw()+
        scale_fill_brewer("Campus",type = "qual")+
        scale_y_continuous(breaks=c(0,max_ecdf/2,max_ecdf),limits=c(0,max_ecdf))+
        ylab("Cases")
        


```


```{r Figure-B2-EpiCurve-7day}

epicurv_df2 <- cases %>% filter(labeldate>(Sys.Date()-7))%>%
                group_by(labeldate,campus)%>%
                summarize(cases=n())

max_ecdf2 <- ceiling(max(epicurv_df2$cases)/2)*2

epicurv_df2%>%
        ggplot(aes(x=labeldate,y=cases,fill=campus))+
        geom_col()+
        theme_bw()+
        scale_fill_brewer("Campus",type = "qual")+
        scale_y_continuous(breaks=c(0,max_ecdf2/2,max_ecdf2),limits=c(0,max_ecdf2))+
        ylab("Cases")
        
        

```


```{r Table-B3-TestSubmitted}
  
  ## all campuses combined, by role in last week:
  ## all campuses combined, cumulative in last week and all time:
    # total tests submitted
    # unique IDs submitting (as prop of all IDs not previously positive)
    # tests per unique ID

```


```{r Table-B4-MostRecentLab}

  ## all campuses combined, by role + total:
    # most recent result positive, neg, incon, invalid
  
```


```{r Figure-B3-PropPositive}

  ## by week, # pos / (# pos + # neg)

```
		
		
```{r Figure-B4-Quar-7day}

  ## number in quarantine, by role. by day, last 7 days

```


```{r Figure-B5-Quar}

  ## number in quarantine, by role. by day, all time

```


```{r Figure-B6-Isol-7day}

  ## number in isolation, by role, by day, last 7 days

```


```{r Figure-B7-Isol}
  
  ## number in isolation, by role, by day, all time

```


## SECTION C: DURHAM CAMPUS

```{r Table-C1-DurhamCond}

  # This Week value + Threshold Indicator, if applicable
    # total active cases from last 10 days
    # active cases per 1000 tested
    # average in isolation over last week
    # average isolation beds in use
    # average number in quarantine this week
    # average quarantine beds in use

```


```{r Figure-C1-EpiCurve}

  ## epi curve, new positive, all time, by day, colored by role

```


```{r Figure-C2-EpiCurve-7day}

  ## epi curve, new positive, last 7 days, by day, colored by role

```


```{r Figure-C3-TestSubmitted}
  
  ## by week, total tests submitted (including repeats), colored by role

```


```{r Figure-C4A-PropPositive}

  ## by week, # pos / (# pos + # neg)

```


```{r Figure-C4B-Map-Active}


```


```{r Figure-C4C-Map-Ever}


```


```{r Table-C2-OnOffCampus}

  # average number daily active cases among students, by dorm vs no dorm
    # current week
    # last week
    # % change
    # sparkline % change all time

```


```{r Table-C3-MostRecentLab}

  ## by role + total, last seven days: most recent result positive, neg, incon, invalid
  
```


```{r Table-C4-TestSubmitted}
  
  ## by role in last week, cumulative in last week and all time:
    # total tests submitted
    # unique IDs submitting (as prop of all IDs not previously positive)
    # tests per unique ID

```


```{r Table-C5-Lab}

  # total number tests submitted by lab, last week + current week, sparkline weekly average over time

```


```{r Figure-C5-Quar}

  ## number in quarantine, colored by quar location, by day, all time

```


```{r Figure-C6-Quar-7day}

  ## number in quarantine, colored by quar location, by day, last 7 days

```


```{r Figure-C7-QuarBeds}

  ## number quarantine beds in use by day

```


```{r Figure-C8-QuarBeds-7day}

  ## number quarantine beds in use by day, past 7 days

```


```{r Figure-C9-Isol}
  
  ## number in isolation, colored by isolation location, by day, all time

```


```{r Figure-C10-Isol-7day}

  ## number in isolation, colored by isolation location, by day, last 7 days

```


```{r Figure-C11-IsolBeds}

  ## number isolation beds in use by day

```


```{r Figure-C12-IsolBeds-7day}

  ## number isolation beds in use by day, past 7 days

```


```{r Table-C6-DetailedTable}

  # Cumulative cases, previous week cases, this week cases, % change this week
    # Total
    # by symptom status
    # by role
    # by age
    # by race/ethnicity
    # by sex at birth
    # by dorm area
    # by college

```


## SECTION D: CONCORD CAMPUS (LAW)

```{r Table-D1-ConcordCond}

  # This Week value + Threshold Indicator, if applicable
    # total active cases from last 10 days
    # active cases per 1000 tested

```


```{r Figure-D1-EpiCurve}

  ## epi curve, new positive, all time, by day, colored by role

```


```{r Figure-D2-EpiCurve-7day}

  ## epi curve, new positive, last 7 days, by day, colored by role

```


```{r Figure-D3-TestSubmitted}
  
  ## by week, total tests submitted (including repeats), colored by role

```


```{r Figure-D4-PropPositive}

  ## by week, # pos / (# pos + # neg)

```


```{r Table-D2-OnOffCampus}

  # average number daily active cases among students, by dorm vs no dorm
    # current week
    # last week
    # % change
    # sparkline % change all time

```


```{r Table-D3-MostRecentLab}

  ## by role + total, last seven days: most recent result positive, neg, incon, invalid
  
```


```{r Table-D4-TestSubmitted}
  
  ## by role in last week, cumulative in last week and all time:
    # total tests submitted
    # unique IDs submitting (as prop of all IDs not previously positive)
    # tests per unique ID

```


```{r Table-D5-Lab}

  # total number tests submitted by lab, last week + current week, sparkline weekly average over time

```


```{r Figure-D5-Quar}

  ## number in quarantine, colored by quar location, by day, all time

```


```{r Figure-D6-Quar-7day}

  ## number in quarantine, colored by quar location, by day, last 7 days

```


```{r Figure-D7-Isol}
  
  ## number in isolation, colored by isolation location, by day, all time

```


```{r Figure-D8-Isol-7day}

  ## number in isolation, colored by isolation location, by day, last 7 days

```


```{r Table-D6-DetailedTable}

  # Cumulative cases, previous week cases, this week cases, % change this week
    # Total
    # by symptom status
    # by role
    # by age
    # by race/ethnicity
    # by sex at birth
    # by dorm area
    # by college

```


## SECTION E: MANCHESTER CAMPUS

```{r Table-E1-ManchCond}

  # This Week value + Threshold Indicator, if applicable
    # total active cases from last 10 days
    # active cases per 1000 tested

```


```{r Figure-E1-EpiCurve}

  ## epi curve, new positive, all time, by day, colored by role

```


```{r Figure-E2-EpiCurve-7day}

  ## epi curve, new positive, last 7 days, by day, colored by role

```


```{r Figure-E3-TestSubmitted}
  
  ## by week, total tests submitted (including repeats), colored by role

```


```{r Figure-E4-PropPositive}

  ## by week, # pos / (# pos + # neg)

```


```{r Table-E2-OnOffCampus}

  # average number daily active cases among students, by dorm vs no dorm
    # current week
    # last week
    # % change
    # sparkline % change all time

```


```{r Table-E3-MostRecentLab}

  ## by role + total, last seven days: most recent result positive, neg, incon, invalid
  
```


```{r Table-E4-TestSubmitted}
  
  ## by role in last week, cumulative in last week and all time:
    # total tests submitted
    # unique IDs submitting (as prop of all IDs not previously positive)
    # tests per unique ID

```


```{r Table-E5-Lab}

  # total number tests submitted by lab, last week + current week, sparkline weekly average over time

```


```{r Figure-E5-Quar}

  ## number in quarantine, colored by quar location, by day, all time

```


```{r Figure-E6-Quar-7day}

  ## number in quarantine, colored by quar location, by day, last 7 days

```


```{r Figure-E7-Isol}
  
  ## number in isolation, colored by isolation location, by day, all time

```


```{r Figure-E8-Isol-7day}

  ## number in isolation, colored by isolation location, by day, last 7 days

```


```{r Table-E6-DetailedTable}

  # Cumulative cases, previous week cases, this week cases, % change this week
    # Total
    # by symptom status
    # by role
    # by age
    # by race/ethnicity
    # by sex at birth
    # by dorm area
    # by college

```

